// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_ERR(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_ERR_NICKNAMEINUSE(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_ERR_NOCHANMODES(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_ERROR(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_INVITE(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_JOIN(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_KICK(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_MODE(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_NICK(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_NOTICE(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_PART(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_PING(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_PONG(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_PRIVMSG(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_QUIT(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_AWAY(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_BANLIST(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_BOUNCE(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_CHANNELMODEIS(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_ENDOFBANLIST(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_ENDOFEXCEPTLIST(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_ENDOFINVITELIST(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_ENDOFMOTD(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_ENDOFNAMES(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_ENDOFWHO(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_EXCEPTLIST(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_INVITELIST(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_LIST(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_LISTEND(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_MOTD(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_NAMREPLY(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_NOTOPIC(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_NOWAWAY(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_TOPIC(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_TRYAGAIN(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_UNAWAY(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_WELCOME(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_RPL_WHOREPLY(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Event_TOPIC(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._GetMessageType(System.String)~Meebey.SmartIrc4net.ReceiveType")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._HandleEvents(Meebey.SmartIrc4net.IrcMessageData)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._InterpretChannelMode(Meebey.SmartIrc4net.IrcMessageData,System.Collections.Generic.List{Meebey.SmartIrc4net.ChannelModeChangeInfo})")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._NextNickname~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._OnConnectionError(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._OnDisconnected(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._RejoinChannels")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._RemoveChannelUser(System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._RemoveIrcUser(System.String)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._StoreChannelsToRejoin")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._SyncingCleanup")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._UnescapeTagValue(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Meebey.SmartIrc4net.IrcClient._Worker(System.Object,Meebey.SmartIrc4net.ReadLineEventArgs)")]
